version: "3"
services:
  sshd:
    build: .
    hostname: sshd
    restart: unless-stopped
    ports:
      - 2222:2222
    environment:
      - PUBLIC_KEY=ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINNvmCMHCiFTjlEF8XS8f2QmCBYygsnQaYHflTjUf5li tunnel